<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\Mapping as ORM;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends \Doctrine\ORM\EntityRepository
{

    /*
     * Find all items
     *
     * return array of items
     */
    public function findAllItemsOrderedByName($pageQName = null)
    {

        if($pageQName !== null)
        {
            $queryQName = 'AND p.qName = :qName ';
        }

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT i '.
                'FROM ShopBundle:Items i, ShopBundle:Page p '.
                'WHERE p.id=i.page '.
                $queryQName.' '.
                'ORDER BY i.name ASC'
            );

        if($pageQName !== null)
        {
            $query->setParameter('qName', $pageQName);
        }

        $items = $query->getResult();

        return $items;

    }

}
