<?php

namespace ShopBundle\Repository;

/**
 * PageElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageElementRepository extends \Doctrine\ORM\EntityRepository
{

    /*
     * Find all pageElements of a page identifying it using its category qName
     *
     * return array of page elements
     */
    public function findAllPageElementsOrderedByPosition($categoryQName = null)
    {

        $pageElements = null
        if($categoryQName !== null)
        {
            $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT c '.
                    'FROM ShopBundle:Category c '.
                    'WHERE c.qName = :qName '
                );
                ->setParameter('qName', $categoryQName);
            $category = $query->getResult();
            if(empty($category)) {
                return null;
            }

            $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT p '.
                    'FROM ShopBundle:Page p'.
                    'WHERE p.category = :category'
                )
                ->setParameter('category', $category->getId());
            $page = $query->getResult();
            if(empty($page) or count($page) > 1) {
                return null;
            }

            $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT pe '.
                    'FROM ShopBundle:PageElement pe '.
                    'WHERE pe.page = :page  '.
                    'ORDER BY pe.position ASC'
                )
                ->setParameter('page', $page->getId());
            $pageElements = $query->getResult();

        }

        return $pageElements;

    }

}
