<?php

namespace ShopBundle\Repository;

/**
 * PageElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageElementRepository extends \Doctrine\ORM\EntityRepository
{
}
