<?php

namespace ShopBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageElementsRepository extends \Doctrine\ORM\EntityRepository
{
}
