<?php

namespace ShopBundle\Repository;

/**
 * PicksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicksRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPicksWithImagesAndTextesAndProducts($id = null)
    {

        if($id === null) {
            return null;
        }
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p '.
                'FROM ShopBundle:Picks p '.
                'WHERE p.id = :id '
            )
            ->setParameter('id', $id);
        $picks = $query->getOneOrNullResult();

        if(in_array(
            $picks->getType(),
            array(
                \ShopBundle\Entity\Picks::PRODUCTS_MANUAL,
                \ShopBundle\Entity\Picks::PRODUCTS_BEST_SALES,
                \ShopBundle\Entity\Picks::PRODUCTS_LAST_SALES
            )
        )) {
           // Get products
           // TODO apply requested rule to select products (last sales, best sales, manual, ...)
           $query = $this->getEntityManager()
               ->createQuery(
                   'SELECT p '.
                   'FROM ShopBundle:Product p '
               );
           $products = $query->getResult();
           foreach($products as $product) {
               $picks->addProduct($product);
           }
        } else if(in_array(
            $picks->getType(),
            array(
                 \ShopBundle\Entity\Picks::PAGES_MANUAL
            )
        )) {
            // Get textes
        } else if(in_array(
            $picks->getType(),
            array(
                 \ShopBundle\Entity\Picks::IMAGES_MANUAL
            )
        )) {
           // Get images
        }

        return $picks;
    }
}
