<?php

namespace ShopBundle\Repository;

/**
 * PicksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicksRepository extends \Doctrine\ORM\EntityRepository
{

    /*
     * Find all products widget
     *
     * return array of products widget
     */
    public function findAllPicksOrderedByName($pageQName = null)
    {

        if($pageQName !== null)
        {
            $queryQName = 'AND p.qName = :qName ';
        }

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT pi '.
                'FROM ShopBundle:Picks pi, ShopBundle:Page p '.
                'WHERE p.id=pi.page '.
                $queryQName.' '.
                'ORDER BY pi.name ASC'
            );

        if($pageQName !== null)
        {
            $query->setParameter('qName', $pageQName);
        }

        $picks = $query->getResult();

        return $picks;

    }

}
