<?php

namespace ShopBundle\Repository;

/**
 * SiteConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteConfigRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Find site by its domain
     *
     * @param string $domain
     *
     * return Site
     */
    public function findSiteConfigByDomain($currentDomain = null)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT sc '.
                'FROM ShopBundle:SiteConfig sc '
            );
        $sites = $query->getResult();

        foreach($sites as $site) {
            $urlParts = parse_url($site->getUrl());
            $domain = $urlParts['host'];  
            if($currentDomain === $domain) {
                return $site;
            }
        }
        return null;
    }

}
