<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\Mapping as ORM;

use ShopBundle\Entity\Slider;
use ShopBundle\Entity\Image;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends \Doctrine\ORM\EntityRepository
{

    /*
     * Find all sliders
     *
     * return array of sliders
     */
    public function findAllWithImagesAndOrderedByName($pageQName = null)
    {

        if($pageQName !== null)
        {
            $queryQName = 'AND p.qName = :qName ';
        }

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT s, si '.
                'FROM ShopBundle:Slider s, ShopBundle:Image si, ShopBundle:Page p '.
                'WHERE s.id=si.slider AND p.id=s.page '.
                $queryQName.' '.
                'ORDER BY s.name ASC'
            );

        if($pageQName !== null)
        {
            $query->setParameter('qName', $pageQName);
        }

        $data = $query->getResult();

        $sliders = array();

        foreach($data as $row) {
            
              if($row instanceof Slider) {
                  $slider = $row;
              }

              if($row instanceof Image) {
	          $sliderImages = $row;
                  $slider->setImage($sliderImages);
              } else {
                  $sliders[] = $slider;
              }

        }

        return $sliders;

    }

}
