<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\Mapping as ORM;

use ShopBundle\Entity\Slider;
use ShopBundle\Entity\Image;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends \Doctrine\ORM\EntityRepository
{

    /*
     * Find slider with images
     *
     * return Slider
     */
    public function findSliderWithImages($id = null)
    {
        if ($id === null) {
            return null;
        }

        // Get slider using its id
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT s '.
                'FROM ShopBundle:Slider s '.
                'WHERE s.id = :id '
            )
            ->setParameter('id', $id);
        $slider = $query->getOneOrNullResult();

        if (!empty($slider)) {
            // Get images associated to this slider
            $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT i '.
                    'FROM ShopBundle:Image i '.
                    'WHERE :slider MEMBER OF i.sliders '
                )
                ->setParameter('slider', $slider->getId());
            $images = $query->getResult();
            foreach ($images as $image) {
                $slider->addImage($image);
            }
        }
        return $slider;
    }
}
