<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\Mapping as ORM;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends \Doctrine\ORM\EntityRepository
{

    /*
     * Find all textes
     *
     * return array of text
     */
    public function findAllTextesOrderedByName($pageQName = null)
    {

        if($pageQName !== null)
        {
            $queryQName = 'AND p.qName = :qName ';
        }

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT t '.
                'FROM ShopBundle:Text t, ShopBundle:Page p '.
                'WHERE p.id=t.page '.
                $queryQName.' '.
                'ORDER BY t.name ASC'
            );

        if($pageQName !== null)
        {
            $query->setParameter('qName', $pageQName);
        }

        $textes = $query->getResult();

        return $textes;

    }

}
