<?php

namespace ShopBundle\Repository;

/**
 * TransactionProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
