fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: ShopBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         %app.path.product_images%
            upload_destination: %kernel.root_dir%/../web/images/local

easy_admin:
    site_name: '<img src="/images/logo.png">'
    list:
        max_results: 100
    design:
        brand_color: 'black'
        color_scheme: 'light'
        menu:
            - label: app.menu.navigation
              children:
                - { entity: 'Category', label: app.menu.categories }
                - { entity: 'Page', label: app.menu.pages }
            - label: app.menu.contents
              children:
                - { entity: 'Text', label: app.menu.textes }
                - { entity: 'Image', label: app.menu.images }
                - { entity: 'Slider', label: app.menu.sliders }
                - { entity: 'Picks', label: app.menu.pickss }
                - { entity: 'PageElement', label: app.menu.pageelements }
            - label: app.menu.shop 
              children:
                - { entity: 'Product', label: app.menu.products }
            - { entity: 'Transaction', label: app.menu.transactions }
            - { entity: 'Transaction', label: app.menu.customers }
            - { entity: 'User', label: app.menu.users }
