imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ShopBundle/Resources/config/config.yml" }
    - { resource: "@AdminBundle/Resources/config/config.yml" }
    - { resource: "@CMSBundle/Resources/config/config.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.product_images: /images/local/


framework:
    #esi:             ~
    translator:      { fallbacks: ["fr"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'XmonColorPickerTypeBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%kernel.root_dir%/Resources/node_modules/.bin/uglifyjs"
        uglifycss:
            bin: "%kernel.root_dir%/Resources/node_modules/.bin/uglifycss"
    assets:
        head:
            inputs:
                - 'vendor/bootstrap/dist/css/bootstrap.min.css'
                - 'vendor/animate.css/animate.min.css'
                - 'vendor/magnific-popup/dist/magnific-popup.css'
                - 'vendor/flexslider/flexslider.css'
                - 'vendor/bxSlider/dist/jquery.bxslider.min.css'
                - 'css/style_main.css'
                - 'css/style.css'
                - 'css/form-elements.css'
                - 'css/media-queries.css'
        bottom:
            inputs:
                - 'vendor/jquery/dist/jquery.min.js'
                - 'vendor/bootstrap/dist/js/bootstrap.min.js'
                - 'vendor/jquery-ui/jquery-ui.min.js'
                - 'vendor/jquery-ui-map/ui/min/jquery.ui.map.min.js'
                - 'vendor/jquery-backstretch/jquery.backstretch.min.js'
                - 'vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js'
                - 'vendor/magnific-popup/dist/jquery.magnific-popup.min.js'
                - 'vendor/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js'
                - 'vendor/flexslider/jquery.flexslider-min.js'
                - 'vendor/bxSlider/dist/jquery.bxslider.min.js'
                - 'vendor/masonry/dist/masonry.pkgd.min.js'
                - 'vendor/wowjs/dist/wow.min.js'
                - 'vendor/selectivizr/selectivizr.js'
                - 'js/retina.min.js'
                - 'js/scripts.js'
                - 'js/main.js'
