shopname:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
