easy_admin:
    entities:
        Category:
            class: ShopBundle\Entity\Category
            controller: AdminBundle\Controller\CategoryController
            label: app.menu.categories
            form:
                title: app.menu.category
                fields:
                    - { type: 'group', label: app.menu.category.group1, help: app.menu.category.group1.help }
                    - { property: 'qName', label: app.menu.category.qName, type: 'text', help: app.menu.category.qName.help }
                    - { property: 'name', label: app.menu.category.name, type: 'text', help: app.menu.category.name.help }
                    - { property: 'parent', label: app.menu.category.parent, type: 'easyadmin_autocomplete', help: app.menu.category.parent.help }
                    - { property: 'rank', label: app.menu.category.rank, type: 'integer', help: app.menu.category.rank.help }
                    - { property: 'shop', label: app.menu.category.shop, type: 'checkbox', help: app.menu.category.rank.help }
                    - property: 'subcategories'
                      label: app.menu.category.subcategories
                      type: 'entity'
                      type_options: { class: 'ShopBundle\Entity\Category', multiple: true }
                    - { property: 'page', label: app.menu.page.parent, type: 'easyadmin_autocomplete', help: app.menu.category.page.help }
                    - { property: 'status', label: app.menu.category.status, type: 'checkbox' }
            show:
                fields:
                    - { property: 'qName', label: app.menu.category.qName }
                    - { property: 'name', label: app.menu.category.name }
                    - { property: 'parent', label: app.menu.category.parent }
                    - { property: 'subcategories', label: app.menu.category.subcategories }
                    - { property: 'rank', label: app.menu.category.rank }
                    - { property: 'shop', label: app.menu.category.shop }
                    - { property: 'page', label: app.menu.category.page }
                    - { property: 'status', label: app.menu.category.status }
            list:
                title: app.menu.categories
                sort: [ 'rank', 'ASC' ]
                actions:
                    - { name: 'show', label: app.menu.actions.show, icon: 'search' }
                    - { name: 'linked', label: app.menu.actions.linked, icon: 'cubes' }
                    - { name: 'moveUpCategory', label: app.menu.actions.moveup, icon: 'arrow-up' }
                    - { name: 'moveDownCategory', label: app.menu.actions.movedown, icon: 'arrow-down' }
                    - { name: 'edit', label: app.menu.actions.edit, icon: 'edit' }
                    - { name: 'delete', label: app.menu.actions.delete, icon: 'trash' }
                fields:
                    - id
                    - { property: 'qName', label: app.menu.category.qName, type: 'text' }
                    - { property: 'name', label: app.menu.category.name, type: 'text' }
                    - { property: 'parent', label: app.menu.category.parent }
                    - { property: 'subcategories', label: app.menu.category.subcategories }
                    - { property: 'rank', label: app.menu.category.rank }
                    - { property: 'page', label: app.menu.category.page }
                    - { property: 'status', label: app.menu.category.status, type: 'toggle' }
